//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacher
    {
        public int tid { get; set; }
        public string tname { get; set; }
        public string taddress { get; set; }
        public Nullable<long> contacts { get; set; }
    }
}
